describe('pizz form App', () => {
    beforeEach(() => {
        cy.visit('http://localhost:3000/pizza')
    })

    const nameInput = () => cy.get('input[name="name"]')
    const sizeInput = () => cy.get('select[name="size"]')
    const pepperoni = () => cy.get('input[name="pepperoni"]')
    const steak = () => cy.get('input[name="steak"]')
    const chicken = () => cy.get('input[name="chicken"]')
    const olives = () => cy.get('input[name="olives"]')
    const form = () => cy.get('.pizza-form')
    const orders = () => cy.get('.orders-section')
    const instructions = () => cy.get('input[name="instructions"]')
    const submitBtn = () => cy.get('button')
    const homeLink = () => cy.get('.home-link')

    it('name input text can be added', () => {
        nameInput()
            .type('Alden Ho')
            .should('have.value', 'Alden Ho')
    })
    it('select multiple toppings', () => {
        pepperoni().check().should('be.checked')
        steak().check().should('be.checked')
        chicken().check().should('be.checked')
        olives().check().should('be.checked')
    })
    it('form submit works', () => {
        nameInput()
            .type('Alden Ho')
        sizeInput()
            .select('medium')
        pepperoni().check()
        steak().check()
        chicken().check()
        olives().check()
        instructions()
            .type('extra cheese')
        form()
            .submit()
        orders()
            .should('contain', 'Alden Ho')
            .should('contain', 'medium')
            .should('contain', 'pepperoni')
            .should('contain', 'steak')
            .should('contain', 'olives')
            .should('contain', 'chicken')
            .should('contain', 'extra cheese')
    })

    it('Home link works', () => {
        homeLink()
            .should('exist')
            .click()
            .url().should('contain', 'http://localhost:3000/')
    })
    it('Button is disabled and enabled correctly', () => {
        submitBtn().should('exist')
        submitBtn().should('be.disabled')
        nameInput().type('Alden Ho')
        sizeInput().select('large')
        submitBtn().should('not.be.disabled')
    })
})